### ISSUE TITLE
[Bug] 遇到僵尸村民立即闪退 MagicLib是最新的MagicLib-mc1.21.1-fabric-0.8.615-beta MasaGadget是最新的MasaGadget-mc1.21-fabric-4.0.364-stable

### ISSUE THREAD

**Issue by zhjc2021** [Hendrix-Shen/MagicLib#100]
### Minecraft Version

1.21.1

### MagicLib Version

0.8.615

### Description

[crash-2024-08-30_14.27.43-client.txt](https://github.com/user-attachments/files/16974693/crash-2024-08-30_14.27.43-client.txt)
[crash-2024-09-12_14.32.23-client.txt](https://github.com/user-attachments/files/16974706/crash-2024-09-12_14.32.23-client.txt)

MagicLib和MasaGadget都是最新版本
遇到僵尸村民就崩溃

### To Reproduce

遇到僵尸村民就崩溃
![image](https://github.com/user-attachments/assets/a2026a2a-17a0-4fb4-9bfe-df12e05559fc)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请参考 #90
