### ISSUE TITLE
[Bug] 在预览比较器时崩溃

### ISSUE THREAD

**Issue by Luck1076** [Hendrix-Shen/MagicLib#101]
### Minecraft Version

1.21

### MagicLib Version

0.8.619

### Description

在使用tweakeroo的容器预览时,预览比较器发生崩溃

### To Reproduce

在使用tweakeroo的容器预览时,预览比较器发生崩溃

### Log

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-09-23 20:09:15
Description: Unexpected error

java.lang.RuntimeException: Exception occurs while delegating events.
  Event class: top.hendrixshen.magiclib.impl.event.minecraft.render.RenderLevelEvent$PostRender
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:51)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatch(EventManager.java:33)
	at net.minecraft.class_761.handler$gcj000$magiclib_minecraft_api$postRenderLevel(class_761.java:14266)
	at net.minecraft.class_761.method_22710(class_761.java:1291)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'top.hendrixshen.magiclib.api.compat.minecraft.network.chat.MutableComponentCompat top.hendrixshen.magiclib.util.minecraft.ComponentUtil.simple(java.lang.Object)'
	at com.plusls.MasaGadget.impl.mod_tweak.tweakeroo.inventoryPreviewSupportComparator.ComparatorInfo.postRenderLevel(ComparatorInfo.java:50)
	at top.hendrixshen.magiclib.impl.event.minecraft.render.RenderLevelEvent$PostRender.dispatch(RenderLevelEvent.java:75)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:48)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:51)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatch(EventManager.java:33)
	at net.minecraft.class_761.handler$gcj000$magiclib_minecraft_api$postRenderLevel(class_761.java:14266)
	at net.minecraft.class_761.method_22710(class_761.java:1291)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 226.680s
	Wall uptime: 187.787s
	High-res time: 169.190s
	Client ticks: 2911 ticks / 145.550s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 3 total; [class_746['luck1076_bot'/4943567, l='ClientLevel', x=713.61, y=119.78, z=394.27], class_745['_TCloudy'/4939692, l='ClientLevel', x=655.35, y=149.51, z=533.52], class_745['luck1076'/4943180, l='ClientLevel', x=646.60, y=149.96, z=529.41]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (55,11,20), Section: (at 7,11,4 in 3,0,1; chunk contains blocks 48,-64,16 to 63,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 70327464 game time, 6088 day time
	Server brand: fabric (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 270

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, annotationtoolbox, appleskin, autofish, betteradvancements, betterbeds, betterconfig, betterf3, betterpingdisplay, c2me, capes, carpet, carpet-ams-addition, carpet-extra, carpet-tis-addition, chat_heads, citresewn, citresewn-defaults, clientcommands, cloth-config, conditional-mixin, continuity, creativecore, custom-crosshair-mod, enhancedblockentities, entityculling, explayerenderer, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fanetlib, fastchest, forgeconfigapiport, gca, ias, ikwid, imblocker, immediatelyfast, inventoryhud, inventoryprofilesnext, iris, itemscroller, jade, krypton, kyrptconfig, letmeclickandsend, libipn, litematica, litematica-server-paster, lithium, magiclib, magiclib-1_21_1, magiclib_core, magiclib_malilib_extra, magiclib_minecraft_api, malilib, masa_gadget_mod, minihud, modernui, modmenu, nochatreports, ommc, pca-protocol, pistorder, placeholder-api, quickshulker, reeses-sodium-options, roughlyenoughitems, simpleblockoverlay, skinlayers3d, sodium, sodium-extra, spark, syncmatica, tweakermore, tweakeroo, world_preview, worldedit, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, betterbeds:fancyconnectedbeds, programmer_art, modmenu_programmer_art, sodium_programmer_art, file/鎶ょ溂澶цˉ涓�20-1.21 .zip, file/XKRD 绾㈡樉v3.3for1.21, continuity:default, file/鍗楃儧鈽嗘灉鍐昏閲弜鏍戝彾楗遍搴�.zip, file/褰╄櫣鍍忕礌RainbowPixel~鈽唙3.5.zip, file/鍗楃儧鈽嗗彲鐖辩洈鐢�, file/褰╄櫣鍍忕礌鈽嗘潙姘戜氦鏄揢I鍒犲噺鍖�.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 641499424 bytes (611 MiB) / 1644167168 bytes (1568 MiB) up to 8791261184 bytes (8384 MiB)
	CPUs: 28
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 28
	Graphics card #0 name: AMD Radeon RX 580 2048SP
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21916.2
	Graphics card #1 name: Intel(R) UHD Graphics 730
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 128.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.101.5535
	Graphics card #2 name: AMD Radeon RX 580 2048SP
	Graphics card #2 vendor: Advanced Micro Devices, Inc.
	Graphics card #2 VRAM (MiB): 8192.00
	Graphics card #2 deviceId: VideoController3
	Graphics card #2 versionInfo: 31.0.21916.2
	Graphics card #3 name: AMD Radeon RX590 GME
	Graphics card #3 vendor: Advanced Micro Devices, Inc.
	Graphics card #3 VRAM (MiB): 8192.00
	Graphics card #3 deviceId: VideoController4
	Graphics card #3 versionInfo: 31.0.21916.2
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 46495.36
	Virtual memory used (MiB): 34603.86
	Swap memory total (MiB): 13824.00
	Swap memory used (MiB): 154.83
	Space in storage for jna.tmpdir (MiB): available: 191569.50, total: 748368.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 191569.50, total: 748368.00
	Space in storage for io.netty.native.workdir (MiB): available: 191569.50, total: 748368.00
	Space in storage for java.io.tmpdir (MiB): available: 53141.62, total: 204800.00
	Space in storage for workdir (MiB): available: 191569.50, total: 748368.00
	JVM Flags: 11 total; -Xmx8374m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		autofish: XPlus Autofish 1.3.3-fabric-mc1.21.x
		betteradvancements: Better Advancements 0.4.2.16
		betterbeds: Better Beds 1.4.0
		betterf3: BetterF3 11.0.1
		betterpingdisplay: Better Ping Display 1.1.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.109+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.109+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.109+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.109+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.109+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.109+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.109+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.109+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		capes: Capes 1.5.4+1.21
		carpet: Carpet Mod 1.4.147+v240613
		carpet-ams-addition: Carpet AMS Addition 2.48.1
			annotationtoolbox: AnnotationToolBox 0.3
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.17
			mixinextras: MixinExtras 0.4.1
		carpet-extra: Carpet Extra 1.4.148
		carpet-tis-addition: Carpet TIS Addition 1.63.1
			conditional-mixin: conditional mixin 0.6.2
		chat_heads: Chat Heads 0.13.1
		citresewn: CIT Resewn 1.2.1+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.1+1.21
		clientcommands: Client Commands 2.9.1
			betterconfig: BetterConfig 1.3
			clientarguments: clientarguments 1.9
			net_fabricmc_mapping-io: mapping-io 0.5.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		custom-crosshair-mod: Custom Crosshair Mod 1.6.0-fabric
		customskinloader: CustomSkinLoader 14.20
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entityculling: EntityCulling 1.7.0
		explayerenderer: ExtraPlayerRenderer 3.0.0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.0
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fastchest: FastChest 1.5+1.20.2
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		gca: GugleCarpetAddition mc1.21-2.9.0+build.52
		ias: In-Game Account Switcher 9.0.1
		ikwid: I Know What I'm Doing 1.0-SNAPSHOT
		imblocker: IMBlocker 4.0.9b
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		inventoryhud: Inventory HUD + 3.4.26
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemphysiclite: ItemPhysicLite 1.6.5
		itemscroller: Item Scroller 0.24.1-sakura.3
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		ksyxis: Ksyxis 1.3.2
		letmeclickandsend: Let Me Click And Send 1.1.0
		libipn: libIPN 6.0.2
		litematica: Litematica 0.19.0
		litematica-server-paster: Litematica Server Paster 1.3.1-SNAPSHOT
			fanetlib: fanetlib 0.1.10
		lithium: Lithium 0.13.1
		magiclib: MagicLib 0.8.619+2bccdb8-beta
			magiclib-1_21_1: MagicLib Legacy Compat for 1.21.1 0.8.30+8d71d8f-beta
			magiclib_core: MagicLib Core API 0.8.129+6b6e507-beta
			magiclib_malilib_extra: MagicLib Malilib API 0.8.55+2bccdb8-beta
			magiclib_minecraft_api: MagicLib Minecraft API 0.6.73+0fd7b58-beta
		malilib: MaLiLib 0.20.3-sakura.2
		masa_gadget_mod: Masa Gadget 4.0.364+496ca1c-stable
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.32.0-sakura.1
		modernui: Modern UI 3.11.0.4
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.7
			com_vladsch_flexmark_flexmark: flexmark 0.64.8
			com_vladsch_flexmark_flexmark-util-ast: flexmark-util-ast 0.64.8
			com_vladsch_flexmark_flexmark-util-builder: flexmark-util-builder 0.64.8
			com_vladsch_flexmark_flexmark-util-collection: flexmark-util-collection 0.64.8
			com_vladsch_flexmark_flexmark-util-data: flexmark-util-data 0.64.8
			com_vladsch_flexmark_flexmark-util-dependency: flexmark-util-dependency 0.64.8
			com_vladsch_flexmark_flexmark-util-format: flexmark-util-format 0.64.8
			com_vladsch_flexmark_flexmark-util-html: flexmark-util-html 0.64.8
			com_vladsch_flexmark_flexmark-util-misc: flexmark-util-misc 0.64.8
			com_vladsch_flexmark_flexmark-util-sequence: flexmark-util-sequence 0.64.8
			com_vladsch_flexmark_flexmark-util-visitor: flexmark-util-visitor 0.64.8
		modmenu: Mod Menu 11.0.2
		nochatreports: No Chat Reports 1.21-v2.8.0
		ommc: Oh My Minecraft Client 0.5.599-wendavid.353+b2f7d75-beta
		pca-protocol: pca protocol 0.3.0
		pistorder: Pistorder 1.6.5-SNAPSHOT
		placeholder-api: Placeholder API 2.4.1+1.21
		quickshulker: Quick Shulker 1.4.4-1.21
			kyrptconfig: Kyrpt Config 1.6.0-1.20.4
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		roughlyenoughitems: Roughly Enough Items 16.0.777
			error_notifier: Error Notifier 1.0.11
		simpleblockoverlay: Simple Block Overlay 1.4.3
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		spark: spark 1.10.97
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		syncmatica: Syncmatica 0.3.12-sakura.6
		tweakermore: TweakerMore 3.20.1
		tweakeroo: Tweakeroo 0.20.999-sakura.19
		world_preview: World preview 1.3.1
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: 1.21-luck1076-backup
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon RX 580 2048SP GL version 4.6.0 Core Profile Context 24.7.1.240618, ATI Technologies Inc.
	Window size: 1920x1017
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/13 chunks
	Resource Packs: vanilla, fabric, annotationtoolbox, appleskin (incompatible), autofish, betteradvancements (incompatible), betterbeds, betterconfig, betterf3, betterpingdisplay, c2me, capes, carpet, carpet-ams-addition, carpet-extra, carpet-tis-addition, chat_heads, citresewn, citresewn-defaults, clientcommands (incompatible), cloth-config, conditional-mixin, continuity, creativecore, custom-crosshair-mod, enhancedblockentities, entityculling, explayerenderer, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fanetlib, fastchest, forgeconfigapiport, gca, ias, ikwid, imblocker (incompatible), immediatelyfast, inventoryhud, inventoryprofilesnext, iris, itemscroller, jade (incompatible), krypton, kyrptconfig, letmeclickandsend, libipn, litematica, litematica-server-paster, lithium, magiclib, magiclib-1_21_1, magiclib_core, magiclib_malilib_extra (incompatible), magiclib_minecraft_api (incompatible), malilib, masa_gadget_mod, minihud, modernui, modmenu, nochatreports, ommc, pca-protocol, pistorder, placeholder-api, quickshulker, reeses-sodium-options, roughlyenoughitems, simpleblockoverlay, skinlayers3d, sodium, sodium-extra, spark (incompatible), syncmatica, tweakermore, tweakeroo (incompatible), world_preview, worldedit (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), betterbeds:fancyconnectedbeds, programmer_art, modmenu_programmer_art, sodium_programmer_art, file/鎶ょ溂澶цˉ涓�20-1.21 .zip, file/XKRD 绾㈡樉v3.3for1.21, continuity:default, file/鍗楃儧鈽嗘灉鍐昏閲弜鏍戝彾楗遍搴�.zip (incompatible), file/褰╄櫣鍍忕礌RainbowPixel~鈽唙3.5.zip (incompatible), file/鍗楃儧鈽嗗彲鐖辩洈鐢� (incompatible), file/褰╄櫣鍍忕礌鈽嗘潙姘戜氦鏄揢I鍒犲噺鍖�.zip (incompatible)
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: GB18030
	CPU: 28x Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请参考 #90
