### ISSUE TITLE
[Feature Request] 更新至1.21.1

### ISSUE THREAD

**Issue by mulletneedle** [Hendrix-Shen/MagicLib#107]
### What new features do you want?

更新至1.21.1

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Crystal0404** [comment]
?
<img width="1046" alt="996b4422e7372332b59ddaf982e6131a" src="https://github.com/user-attachments/assets/2da0e45a-074c-48a6-ac0a-544826ec1003">
