### ISSUE TITLE
Newest release isn't compatible anymore

### ISSUE THREAD

**Issue by sternschnaube** [Hendrix-Shen/MagicLib#12]
### Minecraft Version

1.19.3

### MagicLib Version

0.7.267.209

### Description

![image](https://user-images.githubusercontent.com/120551916/214206018-3c72f3bc-1742-4fab-ba45-f4b289ea57f5.png)

### To Reproduce

/

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Yes, this is an experimental refactoring, there is no mod to adapt it to.
