### ISSUE TITLE
[Bug] Not working in 1.19.2 anymore

### ISSUE THREAD

**Issue by itsMarkiS** [Hendrix-Shen/MagicLib#14]
Minecraft Version
1.19.2

MagicLib Version
last stable one

it says it needs carpet mod... when i download the mod it is incompatible with other mods i use, which was never needed before  //////
![image](https://user-images.githubusercontent.com/47507632/225526618-1858f7be-e900-429f-915b-cdda400e4aad.png)

To Reproduce
install and load

Latest CI build tested
✅ I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
For some reason, MagicLib 0.6 forced a dependency on carpet, so Carpet had to be installed to work properly, this problem has been solved in MagicLib 0.7.

**Comment by Hendrix-Shen** [comment]
Related mods have been updated.
