### ISSUE TITLE
[Question] 缺失： top/hendrixshen/magiclib/config/ConfigManager

### ISSUE THREAD

**Issue by shanghun** [Hendrix-Shen/MagicLib#18]
### Question Type

Others

### Description

magiclib-0.7.295+292b8c3-beta
![image](https://user-images.githubusercontent.com/62878080/228696718-f91dbc26-76b8-4d28-b622-d1e3f0774519.png)

**Comment by shanghun** [comment]
从升级某个mod后就循环报错， 升级完一圈mod后这个又开始报错

**Comment by Hendrix-Shen** [comment]
请发送完整日志。

**Comment by shanghun** [comment]
[2023-03-30-7.log.gz](https://github.com/Hendrix-Shen/MagicLib/files/11110700/2023-03-30-7.log.gz)

**Comment by Hendrix-Shen** [comment]
升级 MasaGadget 和 OMMC。

**Comment by shanghun** [comment]
Perfect.
