### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by acaciachan** [Hendrix-Shen/MagicLib#20]
### Minecraft Version

1.15.2

### MagicLib Version

[CI#253]MagicLib 0.7.302+8d1be4b

### Description

1.15.2 报错内容显示和modmenu冲突

### To Reproduce

[crash-2023-04-13_10.57.37-client.txt](https://github.com/Hendrix-Shen/MagicLib/files/11217755/crash-2023-04-13_10.57.37-client.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by acaciachan** [comment]
这几天更新了masagadget，ommc，pca，magiclib，然后就报错了。考虑到1.15.2旧版和新版的差异已经不小了，不修了的话我继续用旧版的几件套，如果需要的话qq之类的私聊，我可以提供1.15.2的环境。

**Comment by Hendrix-Shen** [comment]
根据日志提供的信息，请在此处 [0.2.74+4879973](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.9) 升级xma。
