### ISSUE TITLE
[Bug]  page not found

### ISSUE THREAD

**Issue by shenjackyuanjie** [Hendrix-Shen/MagicLib#24]
### Minecraft Version

aaaa

### MagicLib Version

aaaa

### Description

aaaaa

### To Reproduce

![image](https://user-images.githubusercontent.com/54507071/232195466-6ef96d12-6e1d-4a5a-a636-a59e7191b3c3.png)

这个release的tag导致时不时就会page not found

https://github.com/Hendrix-Shen/MagicLib/releases/download/dev%2F0.7.258/magiclib-0.7.308+d9af2fc-beta.jar

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 #10 重复。

**Comment by shenjackyuanjie** [comment]
> 与 #10 重复。

修改%2f为/就行吗？
