### ISSUE TITLE
[Bug] 热键重启游戏丢失

### ISSUE THREAD

**Issue by KurisuNya** [Hendrix-Shen/MagicLib#3]
### Minecraft Version

1.17.1

### MagicLib Version

0.5.32

### Description

不知道是不是magiclib的问题，还是说1.17.1的malilib太老了
使用magiclib的两个mod(ommc，tweak-my-client)每次重启游戏都会丢失热键，需要重新设置热键。

### To Reproduce

设置热键后重启游戏，再按下热键发现不起作用，打开配置界面发现热键变成none了。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
此问题应该源自malilib
