### ISSUE TITLE
[Bug] Invalid Modrinth Primary File

### ISSUE THREAD

**Issue by flerouwu** [Hendrix-Shen/MagicLib#36]
### Minecraft Version

1.20.1

### MagicLib Version

0.7.345

### Description

The latest update for [MagicLib on Modrinth](https://modrinth.com/mod/magiclib/version/0.7.345) currently has the 1.14.4 version as the primary file.

### To Reproduce

- Visit the [0.7.345 (latest)](https://modrinth.com/mod/magiclib/version/0.7.345) version of MagicLib on Modrinth.
- Observe that the primary file is set to the 1.14.4 version.

### Expected behavior

The primary file should be the all-inclusive file (`magiclib-all-0.7.345+8caf286-stable.jar`).

### Latest CI build tested

- [ ] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Fixed.
