### ISSUE TITLE
[Bug] Curseforge File Upload Error

### ISSUE THREAD

**Issue by tsx8** [Hendrix-Shen/MagicLib#37]
### Minecraft Version

1.20.1

### MagicLib Version

0.7.345

### Description

![屏幕截图 2023-07-03 115333](https://github.com/Hendrix-Shen/MagicLib/assets/42398191/c0f65cef-03ed-4417-a33b-ab7e2aaf3203)

### To Reproduce

https://www.curseforge.com/minecraft/mc-mods/magiclib/files/4621138

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Fixed, The republished version is [here](https://www.curseforge.com/minecraft/mc-mods/magiclib/files/4622460).
