### ISSUE TITLE
[Bug] 检测不到magiclib

### ISSUE THREAD

**Issue by MCtroplus** [Hendrix-Shen/MagicLib#4]
### Minecraft Version

1.19.1

### MagicLib Version

0.5.35与0.5.35

### Description

同时安装magiclib,tweak my client,OMMC,masa gadget并启动游戏时显示要求安装magiclib 0.5.35或以上版本，手动更改版本检测后仍然无法检测，0.5.34版本也有这种情况，0.5.33正常

### To Reproduce

安装magiclib,OMMC,tweak my client,masa gadget并启动游戏

### Expected behavior

正常启动游戏

### Log

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib, version 0.5.35 or later.
Unmet dependency listing:
	 - Mod 'Masa Gadget' (masa_gadget_mod) 3.0.0-beta+4d26364 requires version 0.5.35 or later of magiclib, which is missing!
	 - Mod 'Oh My Minecraft Client' (ommc) 0.5-beta+a396235 requires version 0.5.34 or later of magiclib, which is missing!
	 - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of magiclib, which is missing!
	 - Mod 'Xaero Map Addition' (xaero_map_addition) 0.2.3 requires version 0.5.30 or later of magiclib, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by MCtroplus** [comment]
0.5.37仍然无法检测

**Comment by MCtroplus** [comment]
使用1.19.2的minecraft与0.5.37的magiclib仍然无法检测到magiclib

**Comment by MCtroplus** [comment]
使用旧版的magiclib会导致OMMC和masa gadget无法使用，使用新版magiclib，改掉OMMC,masa gadget,tweak my client模组检测强行开游戏会导致tweak my client也无法使用
0.5.33 magiclib在modmenu没有显示，但可以支持tweak my client，0.5.34+在modmenu有显示，但没有实际作用

**Comment by Hendrix-Shen** [comment]
请问是用的是独立版本的jar，还是跨版本集成jar？如果 magiclib 使用独立版本文件，则基于此模板开发且依赖magiclib的模组也必须使用单版本文件。

**Comment by MCtroplus** [comment]
> 请问是用的是独立版本的jar，还是跨版本集成jar？如果 magiclib 使用独立版本文件，则基于此模板开发且依赖magiclib的模组也必须使用单版本文件。

懂了，以前看见更新就直接拉到最底下，以后直接找集成版就行了，多谢了
