### ISSUE TITLE
[Bug] Small server log

### ISSUE THREAD

**Issue by sternschnaube** [Hendrix-Shen/MagicLib#43]
### Minecraft Version

1.20.1

### MagicLib Version

Latest

### Description

[MemoryCleaner GC Thread/WARN]: Failed to parse translations from top.hendrixshen.magiclib.language.impl.MagicLanguageResource@ffe76615 (java.lang.IllegalStateException: Array must have size 1, but has size 3)

### To Reproduce

/

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
This issue should be fixed in MagicLib 0.8.

**Comment by sternschnaube** [comment]
Fixed. Thanks 😃
