### ISSUE TITLE
[Bug] minecraft 1.19版本无法使用magiclib（大概

### ISSUE THREAD

**Issue by lsp7878578** [Hendrix-Shen/MagicLib#5]
### Minecraft Version

1.19

### MagicLib Version

0.5.32到0.5.37

### Description

minecraft1.19版本使用magiclib 0.5.32到0.5.34版本无法启动游戏，使用0.5.37可以启动游戏但是以magiclib为前置的mod无法使用

### To Reproduce

使用pcl2启动器版本设置的mod管理功能功能，将0.5.32到0.5.37版本依次启用，0.5.32到0.5.34版本全部启动失败，0.5.37版本启动成功，进入游戏主页面，打开模组菜单mod，点击magiclib，有配置界面按钮，masa gadget和TweakMyClient无配置界面按钮，进入游戏内，默认使用 G + C 打开masa gadget的设置界面无反应，打开游戏内配置 GUI 的TweakMyClient默认热键 T + C 只能打开聊天栏

### Log

[latest.log](https://github.com/Hendrix-Shen/MagicLib/files/9274536/latest.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Minecraft 1.19 请使用 MagicLib 0.5.31。否则其附属模组不会工作

**Comment by lsp7878578** [comment]
> Minecraft 1.19 请使用 MagicLib 0.5.31。否则其附属模组不会工作

原来如此，感谢解答，plc2误我（划掉

**Comment by lsp7878578** [comment]
> Minecraft 1.19 请使用 MagicLib 0.5.31。否则其附属模组不会工作
[错误报告-2022-8-6_15.28.45.zip](https://github.com/Hendrix-Shen/MagicLib/files/9274593/-2022-8-6_15.28.45.zip)
啊这。。。还是启动失败啊

**Comment by 7777777-4547** [comment]
>  错误报告-2022-8-6_15.28.45.zip
>  啊这。。。还是启动失败啊

`	 - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.31!`
Tweak My Client需要0.5.33或以上

**Comment by Ummio** [comment]
> > Minecraft 1.19 请使用MagicLib 0.5.31。否则其附属模组不会工作
> > [错误报告-2022-8-6_15.28.45.zip](https://github.com/Hendrix-Shen/MagicLib/files/9274593/-2022-8-6_15.28.45.zip)
> > 啊这。。。还是启动失败啊

tweakmyclient = =
![img](https://tangbao-1301296093.cos.ap-shanghai.myqcloud.com/blog/bqb/5OAWNP~8U049U6Z%24UYB7%60YU.jpg)

**Comment by lsp7878578** [comment]
> > 错误报告-2022-8-6_15.28.45.zip
> > 啊这。。。还是启动失败啊
> 
> ` - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.31!` Tweak My Client需要0.5.33或以上

妹由想到竟然是这个mod被刺了我

**Comment by Ummio** [comment]
> > > 错误报告-2022-8-6_15.28.45.zip
> > > 啊这。。。还是启动失败啊
> > 
> > 
> > ` - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.31!` Tweak My Client需要0.5.33或以上
> 
> 妹由想到竟然是这个mod被刺了我

![img](https://tangbao-1301296093.cos.ap-shanghai.myqcloud.com/blog/bqb/MD75HAR%60I%25AI%5D%7B%294QIV%24%40XN.gif)

**Comment by lsp7878578** [comment]
> 
![素材1](https://user-images.githubusercontent.com/110713423/183241345-84f2bd5b-9a0f-48c8-9ae3-da9f79a1399f.gif)

**Comment by lsp7878578** [comment]
> > > > 错误报告-2022-8-6_15.28.45.zip
> > > > 啊这。。。还是启动失败啊
> > > 
> > > 
> > > ` - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.31!`调整我的客户端需要0.5.33或以上
> > 
> > 
> > 妹由想到竟然是这个mod被刺了我
> 
> ![img](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) [ ](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) ![断续器](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) [ ](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966)

![素材1](https://user-images.githubusercontent.com/110713423/183241384-434dea70-cb89-40d8-ae3b-7be379b71ded.gif)

**Comment by lsp7878578** [comment]
> > > > 错误报告-2022-8-6_15.28.45.zip
> > > > 啊这。。。还是启动失败啊
> > > 
> > > 
> > > ` - Mod 'Tweak My Client' (tweakmyclient) 3.1.255+af25ac8-stable requires version 0.5.33 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.31!`调整我的客户端需要0.5.33或以上
> > 
> > 
> > 妹由想到竟然是这个mod被刺了我
> 
> ![img](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) [ ](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) ![断续器](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966) [ ](https://camo.githubusercontent.com/e9d7c62745cc8362e7eaeafd73971c1f29c412e5736cd34623cc6cfb0cb50056/68747470733a2f2f74616e6762616f2d313330313239363039332e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f626c6f672f6271622f4d44373548415225363049253235414925354425374225323934514956253234253430584e2e676966)
![素材1](https://user-images.githubusercontent.com/110713423/183241444-ccd21515-42b8-4fa7-9415-b8545b93e5c1.gif)

**Comment by lsp7878578** [comment]
![素材1](https://user-images.githubusercontent.com/110713423/183241489-4b6dcda7-104f-4244-9547-bfa77b0093f1.gif)
