### ISSUE TITLE
[Bug] 和reden同时使用时无法保存reden的设置

### ISSUE THREAD

**Issue by ByakuyX** [Hendrix-Shen/MagicLib#51]
### Minecraft Version

1.20.1

### MagicLib Version

0.7.391+bcc6904-beta

### Description

magiclib和reden同时使用时，每次启动游戏都会弹出reden的隐私设置，且对reden的设置（如快捷键等）在下一次启动游戏时会全部初始化。
modlist：
fabric-api-0.90.7+1.20.1
fabric-carpet-1.20-1.4.112+v230608
fabric-language-kotlin-1.10.14+kotlin.1.9.20
malilib-fabric-1.20.1-0.16.3
owo-lib-0.11.2+1.20
reden-is-what-we-made-0.1.243+d57df07-beta+dev-ci-build.210
magiclib-1.20.1-0.7.391+bcc6904-beta

### To Reproduce

1. 安装reden和其必须的前置
2. 安装magiclib
3. 启动游戏

### Expected behavior

隐私设置应该只在第一次启动时弹出。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by zly2006** [comment]
zly2006/reden-is-what-we-made#49

link一下，如果有进展可以给我同步一下

**Comment by Hendrix-Shen** [comment]
请尝试此版本：[0.7.393+165f6f3](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.7.393)

**Comment by ByakuyX** [comment]
> 请尝试此版本：[0.7.393+165f6f3](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.7.393)

感谢，新版本不会出现此问题了
