### ISSUE TITLE
[Bug] 1.20 版本缺漏

### ISSUE THREAD

**Issue by sasdj2418** [Hendrix-Shen/MagicLib#55]
### Minecraft Version

1.20

### MagicLib Version

0.7.336

### Description

在别人的 1.20 模组包安装全家桶，其中 Masa Gadget  3.2.318 和 ommc 0.5.310 要求 magiclib 至少要  0.7.364，但 magiclib 有 1.20 可用的最多只到 0.7.336 (我是用 all 版，不是单独版)，我知道可以降低 masa gadget 和 ommc 版本来适配，但还是希望提供高版本 magiclib 的 1.20版

### To Reproduce

安装 1.20 可用的 masa 官方全家桶，安装 github 上 1.20 可用的 Masa Gadget 和 oh my minecraft client，安装支持 1.20 的最新版 magiclib

### Expected behavior

正常启动 Minecraft

### Log

安装 magiclib 0.7.336 all 错误信息

> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'MagicLib' (magiclib) 0.7.336+05361cf-stable with version 0.7.364 or later.
> More details:
> 	 - Mod 'Masa Gadget' (masa_gadget_mod) 3.2.318+67ab5b4-stable requires version 0.7.364 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.7.336+05361cf-stable!
> 	 - Mod 'Oh My Minecraft Client' (ommc) 0.5.310+1ca85f5-beta requires version 0.7.345 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.7.336+05361cf-stable!

安装 magicllib 0.7.387 all 错误信息

> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'MagicLib' (magiclib) 0.7.387+c02a0de-stable with version 0.7.364 or later that is compatible with:
> 		 - minecraft 1.20
> More details:
> 	 - Mod 'MagicLib' (magiclib) 0.7.387+c02a0de-stable requires any version between 1.16- (inclusive) and 1.19- (exclusive), version 1.19.2, version 1.19.3, version 1.19.4, any version between 1.20 (exclusive) and 1.20.1 (inclusive) or version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
对 1.20(.0) 的支持期限已经结束了，因此不会添加支持。

**Comment by sasdj2418** [comment]
> 对 1.20(.0) 的支持期限已经结束了，因此不会添加支持。

经过了半年我相信支持期限肯定已结束，我当时已放弃 1.20，实在没想到半年后还会收到回复
