### ISSUE TITLE
[Question] 关于切换设置页面的按钮

### ISSUE THREAD

**Issue by xia-mc** [Hendrix-Shen/MagicLib#62]
### Question Type

Usages

### Description

我注意到在安装magiclib之后，由malilib提供的切换按钮消失了（从配置页面右上角）
这是有意为之的吗？我能通过某种方法重新启用它吗？
谢谢。

**Comment by BAYUNZIYUE** [comment]
切换按钮是 masa gadget 的 快速切换masa mod配置界面 功能 吧
