### ISSUE TITLE
[Question] LGPL 版权声明

### ISSUE THREAD

**Issue by Fallen-Breath** [Hendrix-Shen/MagicLib#71]
### Question Type

Codes

### Description

提交 02d41fae786612f7ccfee7e697bc1ad3fc0b3678 大范围引入了 [tweakermore](https://github.com/Fallen-Breath/tweakermore) 的源代码。请在遵从 LGPLv3 许可的前提下，在提供了原始代码出处的同时，保留原始代码的原始版权和许可声明

缺少版权说明的例子：

- https://github.com/Hendrix-Shen/MagicLib/blob/02d41fae786612f7ccfee7e697bc1ad3fc0b3678/magiclib-minecraft-api/src/main/java/top/hendrixshen/magiclib/impl/render/TextRenderer.java
- https://github.com/Hendrix-Shen/MagicLib/blob/02d41fae786612f7ccfee7e697bc1ad3fc0b3678/magiclib-minecraft-api/src/main/java/top/hendrixshen/magiclib/impl/render/context/RenderGlobal.java
- https://github.com/Hendrix-Shen/MagicLib/blob/02d41fae786612f7ccfee7e697bc1ad3fc0b3678/magiclib-minecraft-api/src/main/java/top/hendrixshen/magiclib/api/render/context/RenderContext.java

缺少出处、版权说明的例子：

- https://github.com/Hendrix-Shen/MagicLib/blob/02d41fae786612f7ccfee7e697bc1ad3fc0b3678/magiclib-minecraft-api/src/main/java/top/hendrixshen/magiclib/util/minecraft/PositionUtil.java

代码来源处的版权说明与下述部分类似

```java
/*
 * This file is part of the TweakerMore project, licensed under the
 * GNU Lesser General Public License v3.0
 *
 * Copyright (C) 2023  Fallen_Breath and contributors
 *
 * TweakerMore is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * TweakerMore is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with TweakerMore.  If not, see <https://www.gnu.org/licenses/>.
 */
```

LGPLv3 相关条款原文（属于 GPLv3 部分）：

> 4. Conveying Verbatim Copies.
You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.
> 5. Conveying Modified Source Versions.
a) The work must carry prominent notices stating that you modified it, and giving a relevant date.

**Comment by Fallen-Breath** [comment]
长话短说，把缺的 license header 补上就好了，毕竟这些代码是大范围的搬运。要带出处链接的话，可以用形如 [这样](https://github.com/Fallen-Breath/tweakermore/blob/10e1a937aadcefb1f2d9d9bab8badc873d4a5b3d/src/main/java/me/fallenbreath/tweakermore/util/render/TextRenderer.java) 的永链，这样能比较好地溯源

**Comment by Fallen-Breath** [comment]
诸如 https://github.com/Hendrix-Shen/MagicLib/commit/70b98ab3df5e67b1f99fb8613dfba547861d8818 等的提交里也有不少 tweakermore 代码的直接使用，也可以补一下 license header，确保 `conspicuously and appropriately publish on each copy an appropriate copyright notice`

**Comment by Hendrix-Shen** [comment]
已按照要求补充原始版权和许可声明，并将出处调整为 GitHub永链。很抱歉出现这样的情况，这块确实疏忽了，没仔细阅读许可协议。
