### ISSUE TITLE
[Question] 可以關掉中文翻譯嗎

### ISSUE THREAD

**Issue by Skywind5487** [Hendrix-Shen/MagicLib#81]
### Question Type

Usages

### Description

一如標題，我的朋友想要有全英文的模組系統，不想要使用i18n

**Comment by Hendrix-Shen** [comment]
删掉对应的翻译文件即可，MagicLib 的翻译是跟随客户端语言的

**Comment by Skywind5487** [comment]
請問翻译文件在哪里? @Hendrix-Shen

**Comment by Hendrix-Shen** [comment]
对应 jar 内的 assets/$namespace/lang/$lang.json

**Comment by Skywind5487** [comment]
thanks!
