### ISSUE TITLE
[Bug] masa全家桶配置界面内不显示右上角的其他masa全家桶模组了

### ISSUE THREAD

**Issue by wearfaa** [Hendrix-Shen/MagicLib#88]
### Minecraft Version

1.20.1

### MagicLib Version

0.8.583

### Description

如题，任意打开masa全家桶文件如tweakroo，看图，右上角原本能切换其他模组 现在我试着降低好几个版本都不行
![1893BCEB576976B6BDB6964F99FCDD48](https://github.com/user-attachments/assets/119d6ba3-6a57-484b-9ef8-8d39044712bb)

### To Reproduce

plz修复

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
快捷切换为 MasaGadGet 模组功能。

**Comment by wearfaa** [comment]
> 快捷切换为 MasaGadGet 模组功能。

模组列表里面搜不到magiclib呢？

**Comment by Hendrix-Shen** [comment]
MagicLib 属于 `library` 类型，Mod Menu 将前置模组设置为 `显示` 才能看到

**Comment by wearfaa** [comment]
> MagicLib 属于 `library` 类型，Mod Menu 将前置模组设置为 `显示` 才能看到

好好好 藏起来了是吧 masagadget找到那个开关了
