### ISSUE TITLE
[Question] Install magiclib-1_19, version 0.5.30 or later.这个是什么

### ISSUE THREAD

**Issue by yakumoice** [Hendrix-Shen/MagicLib#9]
### Question Type

Usages

### Description

0.5.37的1.19.2版本和通用版本都试过了
都会报这个错误
[latest.log](https://github.com/Hendrix-Shen/MagicLib/files/10076341/latest.log)

**Comment by Hendrix-Shen** [comment]
你用的 MasaGadget是1.19的。

**Comment by yakumoice** [comment]
哦哦 这样子）
我以为MasaGadget更新到1.19.2了）
