### ISSUE TITLE
[Bug] 下游模组与 MagicLib 0.8.593+ 不兼容

### ISSUE THREAD

**Issue by snpdzk** [Hendrix-Shen/MagicLib#90]
### Minecraft Version

1.20.1

### MagicLib Version

0.8.593

### Description

预览潜影盒被服务器踢出
![GXO84OG CH{9N)XT$4T6X(8](https://github.com/user-attachments/assets/35616108-9203-4824-bf07-de164b7fa3c8)

### To Reproduce

无

### Expected behavior

可能是因为服务端的pca版本过低（0.2.5和0.3.186）

### Log

https://mclo.gs/a7mrScP

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
暂时不要将 MagicLib 升级到 0.8.593 或更高版本，在 172d126 中存在破坏性改动，请在其他模组明确适应这一更改后再进行更新
